services:
  app:
    build: .
    container_name: meubelpemuda_app
    ports:
      - "4000:4000"
    environment:
      # Host diarahkan ke nama service 'db'
      - DATABASE_URL=mysql://user:devpassword@db:3306/meubelpemuda
      - BETTER_AUTH_SECRET=do813ZGtLJOwlfMhODYDxcUufJJIBMzL
      - BETTER_AUTH_URL=http://localhost:4000
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    container_name: meubelpemuda_db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=meubelpemuda
      - MYSQL_USER=user
      - MYSQL_PASSWORD=devpassword
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
